SELECT * FROM Ecommerce.sellers;

#10 Calculate the total revenue generated by each seller, and rank them by revenue.

SELECT *, DENSE_RANK() OVER(ORDER BY revenue DESC) AS rank_no
FROM
(SELECT order_items.seller_id, SUM(payments.payment_value) revenue
FROM order_items
JOIN payments
ON order_items.order_id = payments.order_id
GROUP BY order_items.seller_id) AS a;

#12 Calculate the cumulative sales per month for each year.
SELECT years, months, payment, SUM(payment) OVER(ORDER BY years, months) AS cumulative_sales
FROM
(SELECT year(orders.order_purchase_timestamp) as years, month(orders.order_purchase_timestamp) as months,
ROUND(SUM(payments.payment_value),2) AS payment
FROM orders
JOIN payments
ON orders.order_id = payments.order_id
GROUP BY years, months
ORDER BY years, months) AS A;

 #13 Calculate the year-over-year growth rate of total sales.
 SELECT year(orders.order_purchase_timestamp) as years,
ROUND(SUM(payments.payment_value),2) AS payment
FROM orders
JOIN payments
ON orders.order_id = payments.order_id
GROUP BY years
ORDER BY years
